# Generated by Django 4.0.1 on 2022-05-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalstore', '0002_alter_gasentry_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasentry',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=b'I01\n'),
        ),
    ]
