# Generated by Django 4.0.1 on 2022-05-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalstore', '0004_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
    ]
