# Generated by Django 4.0.1 on 2022-06-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalstore', '0006_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasentry',
            name='category',
            field=models.CharField(choices=[('mechi', 'mechi'), ('koshi', 'koshi'), ('trisakte', 'trisakte'), ('parajuli', 'parajuli')], max_length=30, null=b'I01\n'),
        ),
    ]
