# Generated by Django 4.0.1 on 2022-06-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalstore', '0008_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasentry',
            name='firm_address',
            field=models.CharField(max_length=30, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='gasentry',
            name='firm_contact',
            field=models.CharField(max_length=30, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='gasentry',
            name='firm_name',
            field=models.CharField(max_length=30, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
