# Generated by Django 4.0.1 on 2022-06-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalstore', '0009_gasentry_firm_address_gasentry_firm_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasentry',
            name='Email',
            field=models.EmailField(max_length=10, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AlterField(
            model_name='gasentry',
            name='firm_contact',
            field=models.CharField(max_length=10, null=b'I01\n'),
        ),
    ]
