# Generated by Django 4.0.1 on 2022-06-01 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalstore', '0010_gasentry_email_alter_gasentry_firm_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasentry',
            name='firm_address',
        ),
    ]
