# Generated by Django 4.0.1 on 2022-06-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalstore', '0011_remove_gasentry_firm_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasentry',
            name='complete_firm_address',
            field=models.CharField(max_length=30, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
