# Generated by Django 4.0.1 on 2022-06-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalstore', '0012_gasentry_complete_firm_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasentry',
            name='complete_firm_address',
            field=models.CharField(max_length=100, null=b'I01\n'),
        ),
    ]
