# Generated by Django 4.0.1 on 2022-06-02 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalstore', '0020_alter_gasentry_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasentry',
            name='firm_name',
        ),
    ]
