# Generated by Django 4.0.1 on 2022-06-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalstore', '0022_alter_gasentry_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
