# Generated by Django 4.0.1 on 2022-06-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalstore', '0025_alter_gasentry_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasentry',
            name='supplier',
        ),
    ]
