# Generated by Django 4.0.1 on 2022-06-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalstore', '0028_gasondemand'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasondemand',
            name='Customer_name',
            field=models.CharField(max_length=30, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
