# Generated by Django 4.0.1 on 2022-06-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalstore', '0030_gasondemand_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasondemand',
            name='stauts',
            field=models.CharField(default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='gasondemand',
            name='customer_contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gasondemand',
            name='required_quantity',
            field=models.IntegerField(),
        ),
    ]
