# Generated by Django 4.0.1 on 2022-06-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalstore', '0031_gasondemand_stauts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasondemand',
            name='supplier',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
