# Generated by Django 4.0.1 on 2022-06-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalstore', '0032_alter_gasondemand_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasondemand',
            name='stauts',
        ),
        migrations.AddField(
            model_name='gasondemand',
            name='status',
            field=models.CharField(default='pending', max_length=30, null=True),
        ),
    ]
