# Generated by Django 4.0.1 on 2022-06-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalstore', '0033_remove_gasondemand_stauts_gasondemand_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasondemand',
            name='required_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
