# Generated by Django 4.0.1 on 2022-06-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalstore', '0034_alter_gasondemand_required_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasondemand',
            name='customer_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gasondemand',
            name='customer_contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gasondemand',
            name='gas_category',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
