# Generated by Django 4.0.1 on 2022-06-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalstore', '0036_alter_gasentry_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasentry',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
