# Generated by Django 4.0.1 on 2022-06-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalstore', '0037_alter_gasentry_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasondemand',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
