# Generated by Django 4.0.1 on 2022-06-27 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generalstore', '0040_alter_gasondemand_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasondemand',
            name='totalgas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='generalstore.gasentry'),
        ),
    ]
