# Generated by Django 4.0.1 on 2022-06-27 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalstore', '0041_gasondemand_totalgas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasondemand',
            name='totalgas',
        ),
    ]
