# Generated by Django 4.0.1 on 2022-06-28 04:41

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('generalstore', '0043_gasondemand_specified_supplier'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gasondemand',
            managers=[
                ('gasondemand', django.db.models.manager.Manager()),
            ],
        ),
    ]
