# Generated by Django 4.0.1 on 2022-06-28 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalstore', '0045_alter_gasondemand_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gasondemand',
            managers=[
            ],
        ),
    ]
