# Generated by Django 4.0.1 on 2022-06-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalstore', '0046_alter_gasondemand_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='gasentry',
            name='category',
            field=models.CharField(max_length=30, null=b'I01\n'),
        ),
    ]
