# Generated by Django 4.0.1 on 2022-06-28 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generalstore', '0047_category_alter_gasentry_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasentry',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='generalstore.category'),
        ),
    ]
