# Generated by Django 4.0.1 on 2022-06-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalstore', '0048_alter_gasentry_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasentry',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
