# Generated by Django 4.0.1 on 2022-06-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalstore', '0050_alter_gasentry_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasondemand',
            name='getby',
            field=models.CharField(max_length=30, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
